### ISSUE TITLE
Replace Priority dropdown with a text input for "Customer Impact"

### ISSUE THREAD

**Issue by rscheuermann** [bennadel/Incident-Commander#9]
We've decided to remove Priority/Severity (P1-P5) from our RCA and IC processes in lieu of focusing on a clear description of the customer impact. See: https://github.com/InVisionApp/engineering-notes/pull/1412

@bennadel - Can you update this tool to also support this change in process? Maybe also it could capture some of the data blocks we're not using for the RCAs? Anything to make our lives simpler!

```
 **Customers impact start**: YYYY-MM-DD HH:mm TZZ
* **Customers impact end**: YYYY-MM-DD HH:mm TZZ
* **Duration**: hh:mm
* **Type of customers affected**: None | Internal | EA | MT | PC (Separate values with a comma if more than one environment was affected)
* **Number of customers affected**: Few | Some | Many | All
* **Features affected**: _(Comma separated list of the affected features)_
* **First Awareness**: Support | Engineering | Customers | Executives
* **Tickets**: [0 via Zendesk](https://invisionapp.zendesk.com/agent/tickets/__TICKET_NUMBER_FROM_INCIDENT__)
* **Tweets**: Yes | No
* **Incident Commander**: __YOUR_NAME__
```

**Comment by bennadel** [comment]
@rscheuermann should be doable. I'll open an internal ticket to track.

**Comment by bennadel** [comment]
@rscheuermann this is done. I've laid the ground-work to differentiate the two types of experiences, mostly so I keep the app backwards-compatible.

![2017-12-16_09-07-11](https://user-images.githubusercontent.com/563690/34071196-a6f25532-e240-11e7-8c7d-39fa8b06d955.png)

**Comment by rscheuermann** [comment]
Thanks @bennadel !
